swiftmailer:
    transport:        smtp
    username:         jalile59@free.fr
    password:         Nasseria59
    host:             smtp.free.fr
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
